collections:
- name: redhat-openshift-5.0.0.tar.gz
  version: 5.0.0
- name: kubernetes-core-6.2.0.tar.gz
  version: 6.2.0
- name: ansible-utils-6.0.0.tar.gz
  version: 6.0.0
- name: amazon-aws-10.1.2.tar.gz
  version: 10.1.2
- name: community-general-12.0.0.tar.gz
  version: 12.0.0
