---
# Quick playbook to deploy Pattern CR with updated Gitea configuration
- name: Deploy Pattern CR using Validated Patterns Operator
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    validated_patterns_pattern_name: "self-healing-platform"
    validated_patterns_git_url: >-
      https://gitea-with-admin-gitea.apps.cluster-fn2qb.fn2qb.sandbox1343.opentlc.com
      /opentlc-mgr/openshift-aiops-platform.git
    validated_patterns_git_revision: "main"
    validated_patterns_target_namespace: "openshift-gitops"
    validated_patterns_values_global: "values-global.yaml"
    validated_patterns_values_hub: "values-hub.yaml"
    project_root: "{{ playbook_dir }}"
    vp_validate_deployment: false

  tasks:
    - name: Deploy Pattern CR
      include_role:
        name: validated_patterns_operator
        tasks_from: main
      vars:
        validated_patterns_pattern_name: "{{ validated_patterns_pattern_name }}"
        validated_patterns_git_url: "{{ validated_patterns_git_url }}"
        validated_patterns_git_revision: "{{ validated_patterns_git_revision }}"
        validated_patterns_target_namespace: "{{ validated_patterns_target_namespace }}"
        validated_patterns_values_global: "{{ validated_patterns_values_global }}"
        validated_patterns_values_hub: "{{ validated_patterns_values_hub }}"
        project_root: "{{ playbook_dir }}"
        vp_validate_deployment: "{{ vp_validate_deployment }}"
